site_name: My MkDocs
site_url: https://example.com
site_author: Your Name
site_description: Documentation powered by MkDocs and Material theme

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: teal
      accent: light blue
    - scheme: slate
      primary: teal
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - OpenWebUI:
      - openwebui/OpenWebui.md
  

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css  # Optional: if you have custom CSS

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourusername

